### ISSUE TITLE
Think about merging this package into opti

### ISSUE THREAD

**Issue by DavidWalz** [basf/doe#3]
DoE depends on `opti` and at this point essentially provides a single user-facing function.
I propose to merge `doe` into `opti`. Since `ipopt` is not a nicely pip-installable depency, this should be done as an optional submodule.

The advantage would be that generic functionality such as the relaxation problem context and the corner point sampling would profit opti as well, and we have less hassle developing a single package.

**Comment by bertiqwerty** [comment]
Agreed.

**Comment by DavidWalz** [comment]
Obsolete with the upcoming transition to bofire.
