### ISSUE TITLE
add D-optimality score

### ISSUE THREAD

**Issue by jsdiazpo** [basf/doe#8]
A nice-to-have method could return a D-optimality score, such as the log-determinant of the information matrix `log(det(X^T X))`. This would allow easy comparison between designs.

**Comment by Osburg** [comment]
Hi :) Such a function already exists, you can find it as `doe.utils.metrics()`. It will also return values for A-optimiality and G-efficiency.

**Comment by jsdiazpo** [comment]
Brilliant! Thanks @Osburg
